DailyReport/urls.py
from django.urls import path
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView, csvdownload


urlpatterns = [
    path('',  ItemFilterView.as_view(), name='index'),
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('create/', ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('csvdownload/', csvdownload, name='csvdownload'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DailyReport.urls'))
]

DailyReport/models.py
import math
from django.db import models
from django.core import validators
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.utils import timezone


def check_age(value):
    f, i = math.modf(value)
    if not (f == 0.0 or f == 0.5) or value > 8:
        raise ValidationError('0.5 刻み、8 以下で入力してください(0, 0.5, 1, 1.5...)')


class Item(models.Model):

    SEX_CHOICES = (
        (1, '男性'),
        (2, '女性'),
        (3, 'テスト'),
    )

    NAME_CHOICES = (
        ('作業者1', '作業者1'),
        ('作業者2', '作業者2'),
        ('作業者3', '作業者3'),
        ('作業者4', '作業者4'),
        ('作業者5', '作業者5'),
        ('作業者6', '作業者6'),
        ('作業者7', '作業者7'),
        ('作業者8', '作業者8'),
        ('作業者9', '作業者9'),
        ('作業者10', '作業者10'),
        ('作業者11', '作業者11'),
        ('作業者12', '作業者12'),
        ('作業者13', '作業者13'),
        ('作業者14', '作業者14'),
        ('作業者15', '作業者15'),
        ('作業者16', '作業者16'),
        ('作業者17', '作業者17'),
        ('作業者18', '作業者18'),
        ('作業者19', '作業者19'),
        ('作業者20', '作業者20'),
        ('作業者21', '作業者21'),
        ('作業者22', '作業者22'),
        ('作業者23', '作業者23'),
        ('作業者24', '作業者24'),
        ('作業者25', '作業者25'),
        ('作業者26', '作業者26'),
        ('作業者27', '作業者27'),
        ('作業者28', '作業者28'),
        ('作業者29', '作業者29'),
        ('作業者30', '作業者30'),
    )

    numeric = RegexValidator(r'^[0-9]*$', 'Only numeric are allowed.')



    name = models.CharField(
        verbose_name='名前',
        choices=NAME_CHOICES,
        max_length=20,
    )

    takuhaikenpin = models.IntegerField(
        verbose_name='宅配検品(@400)',
        # blank=True,
        null=True,
        default=0,
        validators=[validators.MinValueValidator(0),
                  validators.MaxValueValidator(300)]
    )

    sonotakenpin = models.IntegerField(
        verbose_name='その他検品(@200)',
        # blank=True,
        null=True,
        default=0,
        validators = [validators.MinValueValidator(0),
                  validators.MaxValueValidator(999)]
    )

    nyuukosyouhinka = models.IntegerField(
        verbose_name='入庫商品化(@200)',
        # blank=True,
        null=True,
        default=0,
        validators=[validators.MinValueValidator(0),
                    validators.MaxValueValidator(999)]
    )

    shiiresyouhinka = models.IntegerField(
        verbose_name='仕入商品化(@100)',
        # blank=True,
        null=True,
        default=0,
        validators=[validators.MinValueValidator(0),
                  validators.MaxValueValidator(5000)]
    )

    cleaning = models.IntegerField(
        verbose_name='クリーニング(@50)',
        # blank=True,
        null=True,
        default=0,
        validators=[validators.MinValueValidator(0),
                  validators.MaxValueValidator(5000)]
    )

    dataerase = models.IntegerField(
        verbose_name='データイレース(@50)',
        # blank=True,
        null=True,
        default=0,
        validators = [validators.MinValueValidator(0),
                  validators.MaxValueValidator(999)]
    )

    shiirePC = models.IntegerField(
        verbose_name='仕入PC(@1000)',
        # blank=True,
        null=True,
        default=0,
        validators = [validators.MinValueValidator(0),
                  validators.MaxValueValidator(999)]
    )

    tsutaya = models.DecimalField(
        verbose_name='TSUTAYA関連(h)※0.5h刻みで入力',
        blank=True,
        null=True,
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[check_age]
    )

    takuhaikaikon = models.DecimalField(
        verbose_name='宅配開梱(h)※0.5h刻みで入力',
        blank=True,
        null=True,
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[check_age]
    )

    picking = models.DecimalField(
        verbose_name='搬出・ピッキング(h)※0.5h刻みで入力',
        blank=True,
        null=True,
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[check_age]
    )

    datanyuuryoku = models.DecimalField(
        verbose_name='データ入力・画像登録(h)※0.5h刻みで入力',
        blank=True,
        null=True,
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[check_age]
    )

    sex = models.IntegerField(
        verbose_name='性別',
        choices=SEX_CHOICES,
        default=1
    )
    memo = models.TextField(
        verbose_name='備考',
        max_length=300,
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(
        verbose_name='登録日',
        # auto_now_add=True
        default=timezone.now
    )

    # 管理サイト上の表示設定
    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'アイテム'
        verbose_name_plural = 'アイテム'

DailyReport/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ('name', 'takuhaikenpin', 'sonotakenpin', 'nyuukosyouhinka', 'shiiresyouhinka',
                  'cleaning', 'dataerase', 'shiirePC', 'tsutaya', 'takuhaikaikon', 'picking', 'datanyuuryoku',
                  'created_at', 'memo')

        widgets = {
                    #'name': forms.TextInput(attrs={'placeholder':'記入例：山田　太郎'}),
                    'name': forms.Select(),
                    'takuhaikenpin': forms.NumberInput(attrs={'min': 0}),
                    'sonotakenpin': forms.NumberInput(attrs={'min': 0}),
                    'nyuukosyouhinka': forms.NumberInput(attrs={'min': 0}),
                    'shiiresyouhinka': forms.NumberInput(attrs={'min': 0}),
                    'cleaning': forms.NumberInput(attrs={'min': 0}),
                    'dataerase': forms.NumberInput(attrs={'min': 0}),
                    'shiirePC': forms.NumberInput(attrs={'min': 0}),
                    'tsutaya': forms.NumberInput(attrs={'min': 0}),
                    'takuhaikaikon': forms.NumberInput(attrs={'min': 0}),
                    'picking': forms.NumberInput(attrs={'min': 0}),
                    'datanyuuryoku': forms.NumberInput(attrs={'min': 0}),
                    'created_at': forms.DateTimeInput(),

                    #'sex': forms.RadioSelect(), ←ラジオボタン
                    # 'sex': forms.Select(),  # プルダウンセレクト
                    'memo': forms.Textarea(attrs={'rows':4}),
                  }

DailyReport/views.py
import csv
import urllib
import re
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .filters import ItemFilter
from .forms import ItemForm
from .models import Item


# Create your views here.
# 検索一覧画面
class ItemFilterView(LoginRequiredMixin, FilterView):
    model = Item

    # デフォルトの並び順を新しい順とする
    queryset = Item.objects.all().order_by('-created_at')

    # django-filter用設定
    filterset_class = ItemFilter
    strict = False

    # 1ページあたりの表示件数
    paginate_by = 10

    # 検索条件をセッションに保存する
    def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)


# 詳細画面
class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item


# 登録画面
class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 更新画面
class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 削除画面
class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = reverse_lazy('index')


def csvdownload(request):
    """
    csvのdownload実験用
    """
    response = HttpResponse(content_type='text/csv; charset=Shift-JIS')
    filename = urllib.parse.quote((u'日報_' + str(date.today()) + '.csv').encode("utf8"))
    response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'{}'.format(filename)
    writer = csv.writer(response)

    writer.writerow(["氏名", "宅配検品", "その他検品", "入庫商品化", "仕入商品化", "クリーニング", "データイレース",
                     "仕入PC", "ツタヤ関連", "宅配開梱", "搬出・ピッキング", "データ・画像登録", "備考", "登録日",])
    #for item in Item.objects.all():
    for item in Item.objects.filter(created_at__icontains=date.today()):
        #yymmdd = str(item.created_at)
        #str_yymmdd = re.sub('\s\S.*', '', yymmdd)
        #print(str_yymmdd)
        writer.writerow([item.name, item.takuhaikenpin, item.sonotakenpin, item.nyuukosyouhinka, item.shiiresyouhinka,
                         item.cleaning, item.dataerase, item.shiirePC, item.tsutaya, item.takuhaikaikon, item.picking,
                         item.datanyuuryoku, item.memo, item.created_at])
    return response

DailyReport/templates/DailyReport/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>日報登録</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{% static "DailyReport/css/DailyReport.css" %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">日報登録</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">管理者用サイト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout'%}">ログアウト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'csvdownload'%}">本日分Download</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %} 
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "DailyReport/js/plugins/responsive-paginate.js" %}"></script>
    <script src="{% static "DailyReport/js/DailyReport.js" %}"></script>
</body>

</html>

DailyReport/templates/DailyReport/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

DailyReport/templates/DailyReport/csvdownload.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>

</body>
</html>

DailyReport/templates/DailyReport/item_card.html
<div class="row">
    <div class="col-3">
        <p>名前</p>
    </div>
    <div class="col-9">
        <p>{{ item.name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>宅配検品</p>
    </div>
    <div class="col-9">
        <p>{{ item.takuhaikenpin }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>その他検品</p>
    </div>
    <div class="col-9">
        <p>{{ item.sonotakenpin }}</p>
<!--        <p>{{ item.get_sex_display }}</p>-->
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>入庫商品化</p>
    </div>
    <div class="col-9">
        <p>{{ item.nyuukosyouhinka }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>仕入商品化</p>
    </div>
    <div class="col-9">
        <p>{{ item.shiiresyouhinka }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>クリーニング</p>
    </div>
    <div class="col-9">
        <p>{{ item.cleaning }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>データイレース</p>
    </div>
    <div class="col-9">
        <p>{{ item.dataerase }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>仕入PC</p>
    </div>
    <div class="col-9">
        <p>{{ item.shiirePC }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>TSUTAYA関連</p>
    </div>
    <div class="col-9">
        <p>{{ item.tsutaya }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>宅配開梱</p>
    </div>
    <div class="col-9">
        <p>{{ item.takuhaikaikon }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>搬出・ピッキング</p>
    </div>
    <div class="col-9">
        <p>{{ item.picking }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>データ・画像登録</p>
    </div>
    <div class="col-9">
        <p>{{ item.datanyuuryoku }}</p>
    </div>
</div>

<div class="row">
    <div class="col-3">
        <p>備考</p>
    </div>
    <div class="col-9">
        <p>{{ item.memo|linebreaksbr }}</p>
    </div>
</div>

<div class="row">
    <div class="col-3">
        <p>登録日</p>
    </div>
    <div class="col-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

DailyReport/templates/DailyReport/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
<div class="container">
    <h2 class="text-center">データ削除</h2>
    <p>このデータを削除します。よろしいですか？</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
    </form>
</div>

<!-- 1.モーダル表示のためのボタン -->
<button class="btn btn-primary" data-toggle="modal" data-target="#modal-example">
    モーダルダイアログ表示
</button>

<!-- 2.モーダルの配置 -->
<div class="modal" id="modal-example" tabindex="-1">
    <div class="modal-dialog">

        <!-- 3.モーダルのコンテンツ -->
        <div class="modal-content">
            <!-- 4.モーダルのヘッダ -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modal-label">ダイアログ</h4>
            </div>
            <!-- 5.モーダルのボディ -->
            <div class="modal-body">
                ここに内容を書く
            </div>
            <!-- 6.モーダルのフッタ -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                <button type="button" class="btn btn-primary">保存</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

DailyReport/templates/DailyReport/item_confirm_register.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
<div class="container">
    <h2 class="text-center">登録確認画面</h2>
    <p>この日報を登録します。個数や時間の入力内容を確認してください。</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="登録" />
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="登録" />
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

DailyReport/templates/DailyReport/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
	<h2 class="text-center">詳細表示</h2>
	<div class="row">
		<div class="col-12">
			<a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
		</div>
	</div>
	<!--  -->


	{% include "./item_card.html" %}
	<div class="row">
		<div class="col-12">
			<a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
		</div>
	</div>
</div>
{% endblock %}

DailyReport/templates/DailyReport/item_filter.html
{% extends "./_base.html" %}
{% block content %} 
{% load crispy_forms_tags %}
<div class="container">
	<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">検索条件</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<form id="filter" method="get">
					<div class="modal-body">
						{{filter.form|crispy}}
					</div>
				</form>
				<div class="modal-footer">
					<a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>
					<button type="submit" class="btn btn-outline-secondary" form="filter">検索</button>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>

			<div class="float-right">
				<a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
				<a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
			</div>
		</div>
	</div>

	<div class="row" >
		<div class="col-12">
			{% include "./_pagination.html" %}
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			<ul class="list-group">
				{% for item in item_list %}
				<li class="list-group-item">
					<div class="row">
						<div class="col-3">
							<p>名前</p>
						</div>
						<div class="col-9">
							<p>{{ item.name }}</p>
						</div>
					</div>
<!--					<div class="row">-->
<!--						<div class="col-3">-->
<!--							<p>宅配検品</p>-->
<!--						</div>-->
<!--						<div class="col-9">-->
<!--							<p>{{ item.takuhaikenpin }}</p>-->
<!--						</div>-->
<!--					</div>-->
					<div class="row">
						<div class="col-3">
							<p>登録日</p>
						</div>
						<div class="col-9">
							<p>{{item.created_at|date:"Y/m/d G:i:s"}}</p>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<div class="float-right">
								<a class="btn btn-outline-secondary " href="{% url 'detail' item.pk %}">詳細</a>
								<a class="btn btn-outline-secondary " href="{% url 'update' item.pk %}">編集</a>
								<a class="btn btn-outline-secondary " href="{% url 'delete' item.pk %}">削除</a>
							</div>
						</div>
					</div>
				</li>
				{% empty %}
				<li class="list-group-item">
					対象のデータがありません
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	<div class="row" >
		<div class="col-12">
			<div class="float-right">
				<a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
				<a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

DailyReport/templates/DailyReport/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">日報入力画面</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}